version: "3"
services:
  school-database:
    image: fbgonzaga/school-database
    networks:
      - school-network
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3306:3306

networks:
  school-network: 
